name: Add assigned issues to personal project

on:
  issues:
    types: [assigned]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: github.event.assignee.login == 'albegosu'
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/albegosu/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
